### ISSUE TITLE
knowledge_reset

### ISSUE THREAD

**Issue by harithmdnoor** [harithmdnoor/1503_SIT#11]
Clear/reinitialize the knowledge base arrays/structures

**Comment by hafizxa** [comment]
Add this code here. 

`
void knowledge_reset() {

  //Open file with "w" mode will overwrite the existing file making sure it is empty
	fp = fopen(FILE_NAME, "w");

  //Error checking if file cant be opened or dont exist
  if (fp == NULL) {
    perror("Error opening file");
    return 1;
  }

  //Close file
  fclose(fp);

  return;
}`

**Comment by hafizxa** [comment]
Added this constant define incase if reusing this name for later

```
#define FILE_NAME "ICT1503C_Project_Sample.ini"
```
